[package]
name = "typestate-patterns-rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name="simple"
path = "src/simple-pattern.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
